# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# Default scaling factors for velocity and acceleration
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties are defined with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  Revolute_29:
    has_position_limits: true
    min_position: -0.872665
    max_position: 0.785398
    has_velocity_limits: true
    max_velocity: 2.0  # Updated to a more realistic value
    has_acceleration_limits: true
    max_acceleration: 1.0

  Revolute_30:
    has_position_limits: true
    min_position: -0.5
    max_position: 3.316126
    has_velocity_limits: true
    max_velocity: 2.0  # Updated to a more realistic value
    has_acceleration_limits: true
    max_acceleration: 1.0

  Revolute_32:
    has_position_limits: true
    min_position: -0.5
    max_position: 3.316126
    has_velocity_limits: true
    max_velocity: 2.0  # Updated to a more realistic value
    has_acceleration_limits: true
    max_acceleration: 1.0

  Revolute_33:
    has_position_limits: true
    min_position: -0.872665
    max_position: 0.785398
    has_velocity_limits: true
    max_velocity: 2.0  # Updated to a more realistic value
    has_acceleration_limits: true
    max_acceleration: 1.0

  Revolute_35:
    has_position_limits: true
    min_position: -3.316126
    max_position: -0.523599
    has_velocity_limits: true
    max_velocity: 2.0  # Updated to a more realistic value
    has_acceleration_limits: true
    max_acceleration: 1.0

  Revolute_36:
    has_position_limits: true
    min_position: -3.316126
    max_position: -0.523599
    has_velocity_limits: true
    max_velocity: 2.0  # Updated to a more realistic value
    has_acceleration_limits: true
    max_acceleration: 1.0

  Revolute_37:
    has_position_limits: true
    min_position: -0.872665
    max_position: 0.785398
    has_velocity_limits: true
    max_velocity: 2.0  # Updated to a more realistic value
    has_acceleration_limits: true
    max_acceleration: 1.0

  Revolute_38:
    has_position_limits: true
    min_position: -0.872665
    max_position: 0.785398
    has_velocity_limits: true
    max_velocity: 2.0  # Updated to a more realistic value
    has_acceleration_limits: true
    max_acceleration: 1.0

  Revolute_43:
    has_position_limits: true
    min_position: -1.570796
    max_position: 1.570796
    has_velocity_limits: true
    max_velocity: 2.0  # Updated to a more realistic value
    has_acceleration_limits: true
    max_acceleration: 1.0

  Revolute_45:
    has_position_limits: true
    min_position: -1.570796
    max_position: 1.570796
    has_velocity_limits: true
    max_velocity: 2.0  # Updated to a more realistic value
    has_acceleration_limits: true
    max_acceleration: 1.0

  Revolute_46:
    has_position_limits: true
    min_position: -1.570796
    max_position: 1.570796
    has_velocity_limits: true
    max_velocity: 2.0  # Updated to a more realistic value
    has_acceleration_limits: true
    max_acceleration: 1.0

  Revolute_47:
    has_position_limits: true
    min_position: -1.570796
    max_position: 1.570796
    has_velocity_limits: true
    max_velocity: 2.0  # Updated to a more realistic value
    has_acceleration_limits: true
    max_acceleration: 1.0
